[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.111.3"

[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://social.learnaddict.academy/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://social.learnaddict.academy/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/.well-known/nodeinfo*"
  to = "https://social.learnaddict.academy/:splat"
  status = 301
  force = true


